"""set ipcamera.host not unique

Revision ID: 527867bc2b00
Revises: e0b2006e0bd2
Create Date: 2019-08-14 15:28:36.224348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527867bc2b00'
down_revision = 'e0b2006e0bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ip_camera_host', table_name='ip_camera')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ip_camera_host', 'ip_camera', ['host'], unique=1)
    # ### end Alembic commands ###
