"""add port to IPCamera table

Revision ID: e0b2006e0bd2
Revises: 9f91d5dc779f
Create Date: 2019-08-14 00:03:40.077663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b2006e0bd2'
down_revision = '9f91d5dc779f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_camera', sa.Column('port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_camera', 'port')
    # ### end Alembic commands ###
