"""remove unique contraint to ipcamera.host

Revision ID: 796a99c40471
Revises: d7620f0d2a2d
Create Date: 2019-08-14 15:32:06.412130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796a99c40471'
down_revision = 'd7620f0d2a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ip_camera_host', table_name='ip_camera')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ip_camera_host', 'ip_camera', ['host'], unique=True)
    # ### end Alembic commands ###
